(let ((prev nil)
      (cache (make-hash-table :test #'eql))
      (count 1))
(with-open-file (in-stream "input.txt" :direction :input)
    (loop
        (setf prev (read in-stream))
        (incf count)
        (or (read-char in-stream nil nil) (return))
        (setf (gethash prev cache) count)
    )
)
(dotimes (n (- 30000001 count))
 (let ((last-use (or (gethash prev cache) count)))
    (setf (gethash prev cache) count)
    (setf prev (- count last-use))
    (incf count)
 )
)
(print prev)
)